---
title: "Our World in Data: Key Crop Yields"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Our World in Data: Key Crop Yields}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6.5,
  fig.height = 5
)
```

```{r setup}
library(cwdata)
library(tibble)
library(dplyr)
```

# Description

This package provides the "key_crop_yields" dataset, which contains crop yields for countries over time. The yields are measured in tonnes per hectare for `r length(unique(key_crop_yields$crop))` crops (`r
glue::glue_collapse(unique(key_crop_yields$crop),sep = ", ", last = " and ")`). This data is sourced from [Tidy tuesday](https://ourworldindata.org/crop-yields).


```{r}
data("key_crop_yields", package = "cwdata")
crops <- tibble(key_crop_yields)
```


# Exploration of the data
```{r}
library(ggplot2)
crops %>% 
  filter(entity == "Australia") %>% 
  ggplot(aes(x = year, y = tonnes_per_hectare))+
  geom_line()+
  facet_wrap(vars(crop), scales = "free_y")
```






